### ISSUE TITLE
can we do this real time video ?

### ISSUE THREAD

**Issue by sbagadhi** [kishorepv/detect-eye-state#1]
hi , I just wanted to check if we can use these weights to predict the percentage for real time video camera??

**Comment by kishorepv** [comment]
Hi @sbagadhi 
Yes you can do it. Load the frames from your video stream and make predictions on each of them. Combine the frames back to video (opencv should be able to do that with ease)

**Comment by sbagadhi** [comment]
Hi @kishorepv ,

I have been trying to do so with opencv only, but I am not able to figure it out .
can you please help me out with that and I even want the percentage to be displayed on the screen .

can you please guide me on this part.?

**Comment by kishorepv** [comment]
@sbagadhi are you limited to use just opencv? If not, it is pretty easy. You can use `imutils` to capture individual image/frame from a real-time video stream and feed it to the eye state detection model. The prediction/confidence of the model can be annotated on the image using opencv (you can follow the same procedure I used in the code). Then you save these frames to a video using imutils. The process is clearly explained in this post - https://www.pyimagesearch.com/2017/09/18/real-time-object-detection-with-deep-learning-and-opencv/

**Comment by sbagadhi** [comment]
Thank you so much for helping me in this 🙂

Regards,
Shalini Bagadhi
(Associate Data Science)

________________________________

**Comment by kishorepv** [comment]
Sure.
